FROM fschlatt/natural-language-processing-exercises:0.0.1

ADD authorship_verification_trivial.py /code/authorship_verification_trivial.py

ENTRYPOINT [ "python3", "/authership-verification-submission/author-identity.py" ]

# Use the official Python image from Docker Hub
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . .

# Command to run the Python script
CMD ["python", "auther-identity.py"]
